name: Semgrep

on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches: ["master", "main"]
  schedule:
    - cron: '20 17 * * *'

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest

    container:
      image: returntocorp/semgrep

    if: (github.actor != 'dependabot[bot]')

    steps:
      - uses: actions/checkout@v3

      - name: Run Semgrep and generate SARIF file
        run: semgrep ci --sarif ./sarif/results.sarif
        env:
          SEMGREP_RULES: p/default

      - name: Upload SARIF file to code scanning alerts
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ./sarif/results.sarif
